name: mystorekeeper infrastructure
on:
  push:
    branches:
      - dev
      - stage
      - prod
    paths:
      - "cosmosdb/**"
      - "modules/cosmosdb/**"

  workflow_dispatch:
    
env:

  #Global Environment
  GLOBAL_LOCATION: eastus2
  GLOBAL_STORAGE_ACCOUNT_AUTH_MODE: login
  GLOBAL_STORAGE_ACCOUNT_SKU: Standard_ZRS
  GLOBAL_COSMOSDB_CONTAINER_NAME: cosmosdb
  GLOBAL_STORAGE_ACCOUNT_NAME: dspglobalconfigurations
  GLOBAL_RESOURCE_GROUP_NAME: rg-global-configurations

  #Dev Environment
  DEV_LOCATION: eastus2
  DEV_COSMOSDB_NAME: "msk-dev"
  DEV_COSMOSDB_RESOURCE_GROUP: "rg-dev-cosmosdb"
  
  #Stage Environment
  STAGE_LOCATION: eastus
  STAGE_COSMOSDB_NAME: "msk-stage"
  STAGE_COSMOSDB_RESOURCE_GROUP: "rg-stage-cosmosdb"

  #Prod Environment
  PROD_LOCATION: westeurope
  PROD_COSMOSDB_NAME: "msk-prod"
  PROD_COSMOSDB_RESOURCE_GROUP: "rg-prod-cosmosdb"

jobs:

  # Run job when pushed to dev, stage and prod to create storage account to be used for terraform backend configurations
  Global:
    if: ${{ github.ref != 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    name: Global environment
    environment: GLOBAL
    runs-on: ubuntu-22.04
    steps:
      - id: A
        name: checkout repository
        uses: actions/checkout@v3
      - id: B
        name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - id: C
        name: Create resource group
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az group create \
            -n ${{ env.GLOBAL_RESOURCE_GROUP_NAME }} \
            -l ${{ env.GLOBAL_LOCATION }}
      - id: D
        name: Create storage account
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage account create \
            -n ${{ env.GLOBAL_STORAGE_ACCOUNT_NAME }} \
            -g ${{ env.GLOBAL_RESOURCE_GROUP_NAME }} \
            -l ${{ env.GLOBAL_LOCATION }} \
            --sku ${{ env.GLOBAL_STORAGE_ACCOUNT_SKU }}
      - id: E
        name: Create storage container
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage container create \
            -n ${{ env.GLOBAL_COSMOSDB_CONTAINER_NAME }} \
            --account-name ${{ env.GLOBAL_STORAGE_ACCOUNT_NAME }} \
            --auth-mode ${{ env.GLOBAL_STORAGE_ACCOUNT_AUTH_MODE }}

  # Run job when pushed to development environment
  DEV:
    if: ${{ github.ref == 'refs/heads/dev' }}
    environment: DEV
    name: DEV ENV
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./cosmosdb
    needs: [Global]
    steps:
      - id: A
        name: checkout repository
        uses: actions/checkout@v3
      - id: B
        name: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform init \
          -backend-config="storage_account_name=${{ env.GLOBAL_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ env.GLOBAL_COSMOSDB_CONTAINER_NAME }}" \
          -backend-config="resource_group_name=${{ env.GLOBAL_RESOURCE_GROUP_NAME }}" \
          -backend-config="key=dev.tfstate"
      - id: C
        name: terraform fmt
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform fmt
      - id: D
        name: terraform validate
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform validate
      - id: E
        name: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform plan \
          -var="location=${{ env.DEV_LOCATION }}" \
          -var="database-name=${{ env.DEV_COSMOSDB_NAME }}" \
          -var="resource-group=${{ env.DEV_COSMOSDB_RESOURCE_GROUP }}" \
          -var="subscription=${{ secrets.ARM_SUBSCRIPTION_ID }}"
      - id: F
        name: terraform apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform apply \
          -var="location=${{ env.DEV_LOCATION }}" \
          -var="database-name=${{ env.DEV_COSMOSDB_NAME }}" \
          -var="resource-group=${{ env.DEV_COSMOSDB_RESOURCE_GROUP }}" \
          -var="subscription=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
          -auto-approve

  # Run job when pushed to staging environment
  STAGE:
    if: ${{ github.ref == 'refs/heads/stage' }}
    environment: STAGE
    name: STAGE ENV
    runs-on: ubuntu-22.04
    needs: [Global]
    steps:
      - id: A
        name: checkout repository
        uses: actions/checkout@v3
      - id: B
        name: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform init \
          -backend-config="storage_account_name=${{ env.GLOBAL_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ env.GLOBAL_COSMOSDB_CONTAINER_NAME }}" \
          -backend-config="resource_group_name=${{ env.GLOBAL_RESOURCE_GROUP_NAME }}" \
          -backend-config="key=stage.tfstate"
      - id: C
        name: terraform fmt
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform fmt
      - id: D
        name: terraform validate
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform validate
      - id: E
        name: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform plan \
          -var="location=${{ env.STAGE_LOCATION }}" \
          -var="database-name=${{ env.STAGE_COSMOSDB_NAME }}" \
          -var="resource-group=${{ env.STAGE_COSMOSDB_RESOURCE_GROUP }}" \
          -var="subscription=${{ secrets.ARM_SUBSCRIPTION_ID }}"
      - id: F
        name: terraform apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform apply \
          -var="location=${{ env.STAGE_LOCATION }}" \
          -var="database-name=${{ env.STAGE_COSMOSDB_NAME }}" \
          -var="resource-group=${{ env.STAGE_COSMOSDB_RESOURCE_GROUP }}" \
          -var="subscription=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
          -auto-approve

  # Run job when pushed to production environment
  PROD:
    if: ${{ github.ref == 'refs/heads/prod' }}
    environment: PROD
    name: PROD ENV
    runs-on: ubuntu-22.04
    needs: [Global]
    steps:
      - id: A
        name: checkout repository
        uses: actions/checkout@v3
      - id: B
        name: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform init \
          -backend-config="storage_account_name=${{ env.GLOBAL_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ env.GLOBAL_COSMOSDB_CONTAINER_NAME }}" \
          -backend-config="resource_group_name=${{ env.GLOBAL_RESOURCE_GROUP_NAME }}" \
          -backend-config="key=prod.tfstate"
      - id: C
        name: terraform fmt
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform fmt
      - id: D
        name: terraform validate
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform validate
      - id: E
        name: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform plan \
          -var="location=${{ env.PROD_LOCATION }}" \
          -var="database-name=${{ env.PROD_COSMOSDB_NAME }}" \
          -var="resource-group=${{ env.PROD_COSMOSDB_RESOURCE_GROUP }}" \
          -var="subscription=${{ secrets.ARM_SUBSCRIPTION_ID }}"
      - id: F
        name: terraform apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform apply \
          -var="location=${{ env.PROD_LOCATION }}" \
          -var="database-name=${{ env.PROD_COSMOSDB_NAME }}" \
          -var="resource-group=${{ env.PROD_COSMOSDB_RESOURCE_GROUP }}" \
          -var="subscription=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
          -auto-approve
